# Generated by Django 5.1.5 on 2025-01-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('description', models.TextField(verbose_name='Описание рецепта')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ингредиента')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('unit', models.CharField(choices=[('g', 'Граммы'), ('kg', 'Килограммы'), ('ml', 'Миллилитры'), ('l', 'Литры'), ('pcs', 'Штуки')], max_length=10, verbose_name='Единица измерения')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
