# Generated by Django 5.1.4 on 2025-01-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0005_alter_reviews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('в налиции', 'в налиции'), ('нет в наличии', 'нет в наличии')])),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choise_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books')),
            ],
        ),
    ]
