# Generated by Django 5.1.4 on 2025-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, max_length=500, null=True),
        ),
    ]
