# Generated by Django 5.1.5 on 2025-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todomodel_image_url_todomodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
