# Generated by Django 5.1.4 on 2025-01-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_librusec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librusecparser',
            name='date',
        ),
    ]
